### ISSUE TITLE
Seems like it doesn't work with ng-repeat generated headers

### ISSUE THREAD

**Issue by fut33v** [oci-labs/FixedHeader#1]
Table headers, generated by ng-repeat shows like they are regular cells.

**Comment by stevemolitor** [comment]
@fat32nov Can you send us a code snippet demonstrating the problem?  Thanks!

**Comment by fut33v** [comment]
Something like this: http://pastebin.com/HeLFuAG0

**Comment by LMFinney** [comment]
This is a use case we didn't need, but it definitely would be helpful.
You're right, though, that it doesn't work. The jQuery that we use to
decorate the headers doesn't see the <th> elements when they are derived
from an ng-repeat.

Unfortunately, it's not obvious to me how we would fix the directive to
support this.

We might be able to fix this eventually, but we don't have a pending
solution.

**Comment by fut33v** [comment]
Ok, anyway thank you for your reply.

**Comment by fut33v** [comment]
The solution was to add inner div element
http://pastebin.com/VeLzSHMS 
like Miriam Salzer said.

**Comment by LMFinney** [comment]
Thank you for the extra information. I wasn't able to reproduce the solution with just a div - I also had to duplicate the hidden tr in the html code as well. 

So, using a ng-repeat definitely isn't as simple as using manual th's, but it's possible to take advantage of the css styling to get the final effect.

Please see the updated demo files that I just pushed.

Thanks

**Comment by stevemolitor** [comment]
Awesome thanks Lance and Ilya.

Steve
